name: Build Android APK

on:
  push:
    branches:
      - main  # Or whatever your default branch is

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Use a specific Python version

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug
        buildozer_version: stable

    - name: Upload Artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: appwrapper-apk
        path: bin/*.apk